---
title: Occurrence Density by Country - 2019
author: John Waller
date: '2019-08-07'
slug: occurrence-density-by-country
categories:
  - GBIF
tags: []
lastmod: '2019-08-07T09:57:06+02:00'
draft: yes
keywords: []
description: ''
authors: ''
comment: no
toc: ''
autoCollapseToc: no
postMetaInFooter: no
hiddenFromHomePage: no
contentCopyright: no
reward: no
mathjax: no
mathjaxEnableSingleDollar: no
mathjaxEnableAutoNumber: no
hideHeaderAndFooter: no
flowchartDiagrams:
  enable: no
  options: ''
sequenceDiagrams:
  enable: no
  options: ''
---

Here I present a table of occurrence **density** by country. 

1. **Country/Territory** can be any region with an [iso-2 code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2). Only countries larger than 10,000 km<sup>2</sup> are shown. 
2. **Density** is the total number of occurrence records occurring inside the country (Note this does **not** mean the record was necessarily published by the country). 
2. **Change (2017)** is the change in density since 2017. 
3. **Non-bird density** is the total density which is **not coming from class Aves** (i.e. all Plants, Insects, Fungi, other Animals ...). Quite a few countries have very low non-bird density, **meaning most of their occurrence records are birds** (see the **United States**). 
4. **Records** column is the total number of occurrence records on GBIF occurring inside the country (again not necessarily published by the country). 

* For a **csv** of this table with more columns you can go [here](/post/2019-08-07-occurrence-density-by-country_files/export_density_table.tsv). 
* You can see a previous version of this table [here](https://www.gbif.org/mobilization-priorities-2017).


```{R,echo=FALSE,message=FALSE,warning=FALSE}

library(kableExtra)
library(knitr)
library(dplyr)
library(formattable)
library(roperators)

dt = readr::read_tsv("C:/Users/ftw712/Desktop/export_density_table2.tsv")
options(kableExtra.html.bsTable = TRUE)

# dt %>% glimpse()


risen = c("AL","AR","AZ","BO","BR","CI","CM","GA","GE","GW","ID","KH","LT","LV","MA","MD","SL","SN","TG","TZ","UY","VN")

dt %>%
mutate(rank = row_number()) %>%
mutate(note = case_when(
countrycode == "US" ~ "Highest number of total records (<b>450M</b>), but <b>only 5 non-bird records</b> per km<sup>2</sup>. Ranked 37th in non-bird record density (3rd among large countries >500,000km<sup>2</sup>).",
country == "Belize" ~ "Far fewer non-bird records.",
country == "Benin" ~ "Ranks <b>1st</b> in non-bird record density in <b>Africa</b>.",
country == "Kazakhstan" ~ "Ranks <b>last</b> record density in <b>Europe</b>.",
country == "Ukraine" ~ "Ranks <b>last</b> in record density having its entire borders within Europe (Russia and Kazakhstan have lower density), but has <b>doubled</b> record density since 2017.",
country == "South Africa" ~ "Ranks <b>1st</b> in record density in <b>Africa</b>. Ranks <b>4th</b> among large countries (>500,000km<sup>2</sup>).",
country == "Australia" ~ "Ranks <b>5th</b> in record density in among large countries (>500,000km<sup>2</sup>).",
country == "Costa Rica" ~ "Ranks <b>1st</b> in total record density and non-bird density outside of <b>Western Europe</b>",
country == "Netherlands" ~ "Ranks <b>1st</b> in record density, <b>7th in total records (50M) </b>, and <b>1st</b> in non-bird record density with <b>>800 non-bird records/km<sup>2</sup></b>.",
country == "France" ~ "<b>Highest</b> occurrence record density and non-bird density among large countries ( >500,000km<sup>2</sup>).",
countrycode %in% risen ~ "<u><b>Density</b> risen above <b>1 record per km<sup>2</sup></b> since 2017.</u>",
TRUE ~ " ")) %>%
mutate(country_label = 
cell_spec(country_label,
"html",
escape=FALSE,
bold=TRUE,
link="https://www.gbif.org/en/country/"%+% countrycode %+% "/summary",
color = case_when(
occ_record_density > 50 ~ "#4B9E46",
occ_record_density < 50 & occ_record_density > 1 ~ "#34495E",
occ_record_density < 1 ~ "red"
))) %>%
select(rank,country_label,occ_record_density,density_change_from_2017 ,non_bird_density,GBIF_records,suffix,note) %>% 
kable(format = "html", escape = FALSE,
col.names = c(
" ",
"Country/Territory",
"Record Density",
"Change (2017)",
"Non-bird Density",
"Records",
" ",
"Note")) %>% 
column_spec(6,width="3em") %>%
column_spec(2,width="13em") %>%
kable_styling(bootstrap_options = c("hover", "condensed"),fixed_thead = TRUE) %>%
pack_rows("Greater than 50 occurrences per km<sup>2</sup>", 1, 17,escape=FALSE) %>%
pack_rows(" ", 18, 113) %>%
pack_rows("Less than 1 occurrence per km<sup>2</sup>",114,162,escape=FALSE) %>%
row_spec(c(1,5,8,10,18,27,39,63,121,156),background = "#F5F5F5") %>%
row_spec(c(50,87,88,92,93,94,95,96,97,100,101,102,103,104,105,106,107,108,109,110,112,113),background = "#ffff99") 

```

<br>

# Occurrence density for large countries only

Same table as above but for large countries over 500,000 km<sup>2</sup>. 

```{R,echo=FALSE,message=FALSE,warning=FALSE}

library(kableExtra)
library(knitr)
library(dplyr)
library(formattable)
library(roperators)

dt = readr::read_tsv("C:/Users/ftw712/Desktop/export_density_table2.tsv")
options(kableExtra.html.bsTable = TRUE)

# dt %>% glimpse()

risen = c("AL","AR","AZ","BO","BR","CI","CM","GA","GE","GW","ID","KH","LT","LV","MA","MD","SL","SN","TG","TZ","UY","VN")

# %>%
# mutate(note = case_when(
# country == "United States" ~ "Highest number of total records (<b>450M</b>), but <b>only 5 non-bird records</b> per km<sup>2</sup>. Ranked 37th in non-bird record density (3rd among large countries >500,000km<sup>2</sup>).",
# TRUE ~ " "))

dt %>%
filter(area_sqkm > 500e3) %>%
mutate(rank = row_number()) %>%
mutate(note = case_when(
TRUE ~ " ")) %>%
mutate(country_label = 
cell_spec(country_label,
"html",
escape=FALSE,
bold=TRUE,
link="https://www.gbif.org/en/country/"%+% countrycode %+% "/summary",
color = case_when(
occ_record_density > 50 ~ "#4B9E46",
occ_record_density < 50 & occ_record_density > 1 ~ "#34495E",
occ_record_density < 1 ~ "red"
))) %>% 
select(rank,country_label,occ_record_density,density_change_from_2017 ,non_bird_density,GBIF_records,suffix,note) %>% 
kable(format = "html", escape = FALSE,
col.names = c(
" ",
"Country/Territory",
"Record Density",
"Change (2017)",
"Non-bird Density",
"Records",
" ",
"Note")) %>%
column_spec(6,width="3em")  %>%
column_spec(6,width="3em")  %>%
column_spec(2,width="12em") %>%
kable_styling(bootstrap_options = c("hover", "condensed"),fixed_thead = TRUE) %>%
pack_rows("Greater than 50 occurrences per km<sup>2</sup>", 1, 2,escape=FALSE) %>%
pack_rows(" ", 3, 23) %>%
pack_rows("Less than 1 occurrence per km<sup>2</sup>",23,50,escape=FALSE) 
# %>%
# row_spec(c(1,5,8,10,18,27,39,63,121,156),background = "#F5F5F5") %>%
# row_spec(c(50,87,88,92,93,94,95,96,97,100,101,102,103,104,105,106,107,108,109,110,112,113),background = "#ffff99") 

```




<!-- ```{R,echo=FALSE,message=FALSE,warning=FALSE} -->

<!-- library(kableExtra) -->
<!-- library(knitr) -->
<!-- library(dplyr) -->
<!-- library(formattable) -->
<!-- library(roperators) -->

<!-- dt = readr::read_tsv("C:/Users/ftw712/Desktop/table.tsv") -->
<!-- options(kableExtra.html.bsTable = TRUE) -->

<!-- # dt %>% glimpse() -->

<!-- risen = c("AL","AR","AZ","BO","BR","CI","CM","GA","GE","GW","ID","KH","LT","LV","MA","MD","SL","SN","TG","TZ","UY","VN") -->

<!-- dt %>% -->
<!-- mutate(rank = row_number()) %>% -->
<!-- mutate(note = case_when( -->
<!-- country == "United States" ~ "Highest number of total records (<b>450M</b>), but <b>only 5 non-bird records</b> per km<sup>2</sup>. Ranked 37th in non-bird record density (3rd among large countries >500,000km<sup>2</sup>).", -->
<!-- country == "Belize" ~ "Far fewer non-bird records.", -->
<!-- country == "Benin" ~ "Ranks <b>1st</b> in non-bird record density in <b>Africa</b>.", -->
<!-- country == "Kazakhstan" ~ "Ranks <b>last</b> record density in <b>Europe</b>.", -->
<!-- country == "Ukraine" ~ "Ranks <b>last</b> in record density having its entire borders within Europe (Russia and Kazakhstan have lower density), but has <b>doubled</b> record density since 2017.", -->
<!-- country == "South Africa" ~ "Ranks <b>1st</b> in record density in <b>Africa</b>. Ranks <b>4th</b> among large countries (>500,000km<sup>2</sup>).", -->
<!-- country == "Australia" ~ "Ranks <b>5th</b> in record density in among large countries (>500,000km<sup>2</sup>).", -->
<!-- country == "Costa Rica" ~ "Ranks <b>1st</b> in total record density and non-bird density outside of <b>Western Europe</b>", -->
<!-- country == "Netherlands" ~ "Ranks <b>1st</b> in record density, <b>7th in total records (50M) </b>, and <b>1st</b> in non-bird record density with <b>>800 non-bird records/km<sup>2</sup></b>.", -->
<!-- country == "France" ~ "<b>Highest</b> occurrence record density and non-bird density among large countries ( >500,000km<sup>2</sup>).", -->
<!-- countrycode %in% risen ~ "<u><b>Density</b> risen above <b>1 record per km<sup>2</sup></b> since 2017.</u>", -->
<!-- TRUE ~ " ")) %>% -->
<!-- mutate(country =  -->
<!-- cell_spec(country, -->
<!-- "html", -->
<!-- escape=FALSE, -->
<!-- bold=TRUE, -->
<!-- link="https://www.gbif.org/en/country/"%+% countrycode %+% "/summary", -->
<!-- color = case_when( -->
<!-- density > 50 ~ "#4B9E46", -->
<!-- density < 50 & density > 1 ~ "#34495E", -->
<!-- density < 1 ~ "red" -->
<!-- ))) %>% -->
<!-- select(rank,country,density,density_change,non_bird_density,GBIF_records,suffix,note) %>%  -->
<!-- kable(format = "html", escape = FALSE, -->
<!-- col.names = c( -->
<!-- " ", -->
<!-- "Country/Territory", -->
<!-- "Record Density", -->
<!-- "Change (2017)", -->
<!-- "Non-bird Density", -->
<!-- "Records", -->
<!-- " ", -->
<!-- "Note")) %>%  -->
<!-- column_spec(6,width="3em") %>% -->
<!-- column_spec(2,width="12em") %>% -->
<!-- kable_styling(bootstrap_options = c("hover", "condensed"),fixed_thead = TRUE) %>% -->
<!-- pack_rows("Greater than 50 occurrences per km<sup>2</sup>", 1, 17,escape=FALSE) %>% -->
<!-- pack_rows(" ", 18, 113) %>% -->
<!-- pack_rows("Less than 1 occurrence per km<sup>2</sup>",114,162,escape=FALSE) %>% -->
<!-- row_spec(c(1,5,8,10,18,27,39,63,121,156),background = "#F5F5F5") %>% -->
<!-- row_spec(c(50,87,88,92,93,94,95,96,97,100,101,102,103,104,105,106,107,108,109,110,112,113),background = "#ffff99")  -->

<!-- ``` -->



<!--more-->
